INSERT INTO moon (name, description, diameter_km, distance_from_earth_light_years, age_in_million_years, discovered_before_20th_century, reached_by_space_probe)
VALUES  
  ('Moon', 'The only natural satellite of Earth. It is the fifth largest moon in the Solar system.', 3474, 0, 4.5, True, True),
  ('Io', 'A volcanic moon of Jupiter. It is the most volcanically active body in the Solar system.', 3642, 5, 4.5, True, True),
  ('Europa', 'A moon of Jupiter. It is thought to have a liquid ocean beneath its icy surface.', 3122, 5, 4.5, True, False),
  ('Ganymede', 'A moon of Jupiter. It is the largest moon in the Solar system.', 5268, 5, 4.5, True, False),
  ('Callisto', 'A moon of Jupiter. It is the second largest moon in the Solar system.', 4821, 5, 4.5, True, False),
  ('Titan', 'A moon of Saturn. It is the second largest moon in the Solar system. It has a thick atmosphere and is thought to have lakes of liquid methane on its surface.', 5150, 9, 4.5, True, False),
  ('Rhea', 'A moon of Saturn. It is the third largest moon in the Solar system. It is thought to have a liquid ocean beneath its icy surface.', 1528, 9, 4.5, True, False),
  ('Iapetus', 'A moon of Saturn. It has a large, dark side and a light side.', 1476, 9, 4.5, True, False),
  ('Dione', 'A moon of Saturn. It is thought to have a liquid ocean beneath its icy surface.', 1120, 9, 4.5, True, False),
  ('Tethys', 'A moon of Saturn. It is thought to have a liquid ocean beneath its icy surface.', 1092, 9, 4.5, True, False),
  ('Calypso', 'A moon of Saturn. It is one of the many moons of Saturn that are thought to be captured asteroids.', 480, 9, 4.5, True, False),
  ('Telesto', 'A moon of Saturn. It is one of the many moons of Saturn that are thought to be captured asteroids.', 480, 9, 4.5, True, False),
  ('Proteus', 'A moon of Neptune. It is the largest moon of Neptune that is not in a regular orbit.', 1188, 30, 4.5, True, False),
  ('Triton', 'A moon of Neptune. It is the largest moon of Neptune and is thought to be a captured Kuiper Belt object.', 2706, 30, 4.5, True, False),
  ('Nereid', 'A moon of Neptune. It is the second largest moon of Neptune. It has a very elongated orbit.', 1704, 30, 4.5, True, False),
  ('Charon', 'The largest moon of Pluto. It is thought to have formed from a collision between Pluto and another object.', 1207, 39, 4.5, True, False),
  ('Nix', 'A moon of Pluto. It is thought to be a captured Kuiper Belt object.', 49, 39, 4.5, True, False),
  ('Kerberos', 'A moon of Pluto. It is thought to be a captured Kuiper Belt object.', 12, 39, 4.5, True, False),
  ('Styx', 'A moon of Pluto. It is thought to be a captured Kuiper Belt object.', 9, 39, 4.5, True, False),
  ('Dia', 'A moon of Uranus. It is one of the many moons of Uranus that are thought to be captured asteroids.', 555, 19, 4.5, True, False),
  ('Krewe', 'A moon of Uranus. It is one of the many moons of Uranus that are thought to be captured asteroids.', 190, 19, 4.5, True, False),
  ('Miranda', 'A moon of Uranus. It is thought to have been formed from a collision between Uranus and another object.', 500, 19, 4.5, True, False),
  ('Ariel', 'A moon of Uranus. It is thought to have been formed from a collision between Uranus and another object.', 1158, 19, 4.5, True, False),
  ('Umbriel', 'A moon of Uranus. It is thought to have been formed from a collision between Uranus and another object.', 1170, 19, 4.5, True, False),
  ('Titania', 'A moon of Uranus. It is the largest moon of Uranus.', 1578, 19, 4.5, True, False),
  ('Oberon', 'A moon of Uranus. It is the second largest moon of Uranus.', 1526, 19, 4.5, True, False)
  ;