INSERT INTO planet (name, description, diameter_km, distance_from_earth_light_years, age_in_million_years, discovered_before_20th_century, reached_by_space_probe)
VALUES
  ('Mercury', 'A small, rocky planet that is the closest to the Sun. It has no atmosphere and is covered in craters.', 4878, 0, 4.5, False, False),
  ('Venus', 'A hot, dense planet that is covered in clouds of sulfuric acid. It is the hottest planet in the Solar system.', 12756, 0, 4.5, False, False),
  ('Earth', 'The only planet known to support life. It is a blue planet with a large ocean and a variety of climates.', 12756, 1, 4.5, False, True),
  ('Mars', 'A cold, dry planet with a thin atmosphere. It is the fourth planet from the Sun and is the second smallest planet in the Solar system.', 6792, 1, 4.5, False, False),
  ('Jupiter', 'A large, gas giant that is the largest planet in the Solar system. It has a strong magnetic field and a thick atmosphere.', 142984, 5, 4.5, False, False),
  ('Saturn', 'A gas giant that is the second largest planet in the Solar system. It is known for its rings, which are made up of ice and dust.', 120536, 9, 4.5, False, False),
  ('Uranus', 'A gas giant that is tilted on its side. It is known for its blue-green color.', 51118, 19, 4.5, False, False),
  ('Neptune', 'A gas giant that is the farthest planet from the Sun. It is known for its Great Dark Spot, which is a large storm similar to the Great Red Spot on Jupiter.', 49532, 30, 4.5, False, False),
  ('Proxima Centauri b', 'A rocky planet that orbits Proxima Centauri, the closest star to the Sun. It is the first planet to be found in the habitable zone of another star.', 1300, 4, 4.8, False, False),
  ('Proxima Centauri c', 'A gas giant that orbits Proxima Centauri. It is much larger than Proxima Centauri b, and is not in the habitable zone.', 4200, 4, 1.2, False, False),
  ('Alpha Centauri A b', 'A gas giant that orbits Alpha Centauri A, the larger of the two stars in the Alpha Centauri binary system. It is not in the habitable zone.', 11200, 4, 4.5, False, False),
  ('Alpha Centauri B b', 'A gas giant that orbits Alpha Centauri B, the smaller of the two stars in the Alpha Centauri binary system. It is not in the habitable zone.', 7100, 4.3, 4.5, False, False),
  ('Alpha Centauri B c', 'A rocky planet that orbits Alpha Centauri B. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 1400, 4, 4.5, False, False),
  ('TRAPPIST-1b', 'A rocky planet that orbits Trappist-1, a red dwarf star. It is the closest planet to its star, and has an orbital period of just 1.5 days.', 1700, 40, 4.5, False, False),
  ('TRAPPIST-1c', 'A rocky planet that orbits Trappist-1. It is slightly larger than TRAPPIST-1b, and has an orbital period of just 2.4 days.', 2400, 40, 4.5, False, False),
  ('TRAPPIST-1d', 'A rocky planet that orbits Trappist-1. It is slightly larger than TRAPPIST-1c, and has an orbital period of just 4.0 days.', 3100, 40, 4.5, False, False),
  ('TRAPPIST-1e', 'A rocky planet that orbits Trappist-1. It is slightly larger than TRAPPIST-1d, and has an orbital period of just 6.0 days.', 4000, 40, 4.5, False, False),
  ('TRAPPIST-1f', 'A rocky planet that orbits Trappist-1. It is slightly larger than TRAPPIST-1e, and has an orbital period of just 9.0 days.', 5000, 40, 4.5, False, False),
  ('Kepler-452b', 'A rocky planet that orbits Kepler-452, a G2V star that is similar to the Sun. It is the first planet to be found in the habitable zone of another star.', 1400, 1402, 4.5, False, False),
  ('Kepler-452c', 'A gas giant that orbits Kepler-452. It is much larger than Kepler-452b, and is not in the habitable zone.', 4800, 1402, 4.5, False, False),
  ('Kepler-452d', 'A rocky planet that orbits Kepler-452. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 1200, 1402, 4.5, False, False),
  ('Kepler-452e', 'A gas giant that orbits Kepler-452. It is not in the habitable zone.', 8800, 1402, 4.5, False, False),
  ('Kepler-452f', 'A rocky planet that orbits Kepler-452. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 1000, 1402, 4.5, False, False),
  ('HD 10180 b', 'A rocky planet that orbits HD 10180, a G-type star that is similar to the Sun. It is the first planet to be found in the habitable zone of another star.', 1300, 127, 4.5, False, False),
  ('HD 10180 c', 'A gas giant that orbits HD 10180. It is much larger than HD 10180 b, and is not in the habitable zone.', 4200, 127, 1.2, False, False),
  ('HD 10180 d', 'A gas giant that orbits HD 10180. It is not in the habitable zone.', 11200, 127, 4.5, False, False),
  ('HD 10180 e', 'A gas giant that orbits HD 10180. It is not in the habitable zone.', 7100, 127, 4.5, False, False),
  ('HD 10180 f', 'A rocky planet that orbits HD 10180. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 1400, 127, 4.5, False, False),
  ('GJ 667Cc', 'A rocky planet that orbits GJ 667C, a red dwarf star. It is the first planet to be found in the habitable zone of another star.', 1700, 22, 4.5, False, False),
  ('GJ 667Cb', 'A gas giant that orbits GJ 667C. It is much larger than GJ 667Cc, and is not in the habitable zone.', 4200, 22, 1.2, False, False),
  ('GJ 667Ce', 'A rocky planet that orbits GJ 667C. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 2400, 22, 4.5, False, False),
  ('GJ 667Cf', 'A rocky planet that orbits GJ 667C. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 3100, 22, 4.5, False, False),
  ('GJ 667Cg', 'A gas giant that orbits GJ 667C. It is not in the habitable zone.', 7100, 22, 4.5, False, False),
  ('Kepler-186f', 'A rocky planet that orbits Kepler-186, a red dwarf star. It is the first planet to be found in the habitable zone of another star.', 11100, 490, 4.5, False, False),
  ('Kepler-186b', 'A gas giant that orbits Kepler-186. It is much larger than Kepler-186f, and is not in the habitable zone.', 4.2, 490, 1.2, False, False),
  ('Kepler-186c', 'A rocky planet that orbits Kepler-186. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 2400, 490, 4.5, False, False),
  ('Kepler-186d', 'A rocky planet that orbits Kepler-186. It is in the habitable zone, but is too small to be considered a likely candidate for life.', 3100, 490, 4.5, False, False),
  ('Kepler-186e', 'A gas giant that orbits Kepler-186. It is not in the habitable zone.', 7.1, 490, 4.5, False, False)
  ;